using System.Collections.Generic;
using System.Linq;
using RNAssistant.Core.Models;

namespace RNAssistant.Office.Services
{
    internal static class BuiltInSkillProvider
    {
        public static IReadOnlyList<SkillDefinition> GetSkills(IOfficeApplicationAdapter adapter)
        {
            var result = new List<SkillDefinition>
            {
                Skill(
                    "common.task_tracking",
                    "Task tracking",
                    "Create and maintain a temporary visible checklist for work with at least three meaningful stages.",
                    "# Task Tracking\n\nUse this skill for at least three explicit deliverables or meaningful user-level stages, or a real discovery -> construction -> verification workflow. Do not turn individual reads or tool calls into artificial tasks. Loading this skill does not load the tool schema: load exact `common.task_list_set` through `common.capabilities_read` and wait for its successful schema result before first use.\n\n## Create before domain work\n\n- Before the first Office/source read or mutation, call `common.task_list_set` with `action=save`, one concise goal, and the complete ordered execution stages. Use at least three stages because the schema requires it; keep at most one `in_progress`. Supply only step text/status. Runtime owns list and stable step ids.\n- Stages describe user-visible outcomes such as inspect source, build the primary result, bind/test, and verify. They do not enumerate capability reads, confirmations, or each file write.\n- The Task List is the execution plan in Agent mode. It is not a separate strategic Plan document, execution authority, hidden reasoning, or proof of success.\n\n## Maintain and close\n\n- Save the complete current list after material progress or a material scope/error change. If a failed call leaves work possible, keep the stage `in_progress`; use `blocked` only for a real blocker. Never hide or remove an unmet requested deliverable.\n- Mark `completed` only after matching `TOOL_RESULT status=ok` plus evidence for that stage. Tool success does not by itself prove an applied effect; a verified no-op may also be ok.\n- If the active list is outside context, find it with `common.resources_find` in conversation scope and read the exact semantic target. Never pass a resource URI, revision, cursor, list id, or step id.\n- Before a successful final answer, make every step terminal, save the complete state, then call `common.task_list_set` with `action=close` and `outcome=completed`. An open active Task List means the run is not successfully finished; if closing fails, say that explicitly instead of claiming completion. Use `cancelled` or `superseded` only when that is the honest terminal outcome."),
                Skill(
                    "common.text_search_replace",
                    "Text search and replace",
                    "Find and safely replace literal or regex text in Office content.",
                    "# Text Search and Replace\n\nUse this skill for bounded search or replacement in Office text/cells. Use the exact host pair when available: `excel.find_cells` / `excel.replace_cells`, `word.find_text` / `word.replace_text`, or `powerpoint.search_text` / `powerpoint.replace_text`. Outlook exposes read-only `outlook.search_mail`; it has no replace operation.\n\n- Search first when discovery, coordinates, ambiguity review, or a broad-impact preview is needed; it is not a mandatory precondition for a narrow replacement.\n- Prefer literal mode unless the user needs a pattern. Use regex capture groups only in regex mode. Keep scope as narrow as practical and review returned coordinates/previews for broad edits.\n- Replacement tools reread the current scope under the mutation lock, enforce `maxReplacements`, and verify read-back. Do not invent or pass match-count/hash guards.\n- Regex and bulk replacement require confirmation. Finish only from the replacement result evidence; a search result alone proves no mutation."),
                Skill(
                    "common.vba_code_editing",
                    "VBA code editing",
                    "Safely inspect, create, rename, refactor, patch, delete, or restore VBA macros and components in Excel, Word, or PowerPoint. Use whenever a request changes VBA source or component identity.",
                    "# VBA Code Editing\n\n" +
                    "## Choose the operation\n\n" +
                    "- For a project-wide VBA question, read `RUNTIME_CONTEXT.document.vba_project_target` directly with `common.resources_read` and representation `structure`; this is the complete component inventory for the exact bound document. If that target is unavailable, browse `common.resources_find` with scope `vba` and no query, then read the first `VBA project` target. Use a query only to find a specific module: it is filtered search, not project inventory. Read a component target with representation `source`; one successful result contains the complete representation. Use scope `backups` only for recovery evidence. After `resource_revision_changed`, repeat the read. URI, revision, cursor, provider, and provider-specific kind are runtime-owned.\n" +
                    "- For whole-source write, use `common.vba_write_module` only when you have the complete intended module source. Default `mode=upsert` updates or creates; `componentType` matters only on creation. Use `createOnly` or `updateOnly` only when existence itself must be guarded. Continue with the actual normalized name returned by the tool.\n" +
                    "- Use `common.vba_apply_patch` only for an existing component. It never creates a missing module: when the target is absent, switch to `common.vba_write_module` with the full source and component type.\n" +
                    "- For an identity-preserving rename, call `common.vba_rename_module` with exactly `moduleName` and `newModuleName`. Runtime guards both names, rejects collisions, journals the old and new identities, and preserves source/type. Rename supports StdModule, ClassModule, and blank code-only MSForm, but not document modules. It does not rewrite explicit references such as `OldModule.Run`; search and update those deliberately. Never imitate rename with write plus delete.\n\n" +
                    "## Patch without corrupting code\n\n" +
                    "- Pass `patch` as a native JSON array, never stringified JSON. Put all edits derived from one complete source snapshot into that one ordered patch call: runtime applies every hunk in memory, validates one final source and performs one write, or writes nothing. Each hunk requires `find` and `text`; when `find` repeats inside the selected module, add exact unchanged `contextBefore` and/or `contextAfter`. Context is verified but not replaced. The fixed replace operation belongs to runtime. There are no line-number, fuzzy, first-match, regex, or implicit insertion modes. Every later hunk sees the result of earlier hunks.\n" +
                    "- An exact replacement whose `find` and `text` already match is an idempotent no-op and is skipped. If every hunk is a no-op, the tool succeeds without a document write or journal mutation.\n" +
                    "- Copy `find` from a fresh complete `common.resources_read` source result. Keep the replacement boundary exact; if that source occurs more than once, copy immediately adjacent unchanged source into `contextBefore`/`contextAfter` until the combined block has one case-sensitive match. Missing, ambiguous, or stale context writes nothing and must be re-read, never retried unchanged.\n" +
                    "- For insertion, repeat the exact anchor block in `text` and add new code before or after it. Runtime preserves string contents and boundary newlines, normalizing only LF/CRLF to the current module style. For deletion, use empty `text`.\n" +
                    "- Never rebuild an existing module with `common.vba_write_module` unless the complete intended source is present in active context; patch exact current hunks instead. Use whole-source write only when the complete intended module is known.\n" +
                    "- Before calling write or patch, self-check the final module source for duplicated `Sub`, `Function`, or same `Property Get/Let/Set` declarations. Remove superseded earlier copies inside the intended edit; if intent is unclear, stop. Runtime rejects duplicate procedure/property declarations before journal and dispatch with `vba_code_invalid`.\n" +
                    "- Keep every `End Sub`, `End Function`, `End Property`, `End Type`, and `End Enum` on its own logical line. JSON transport may display `\\\"`, but live VBA source must use doubled quotes (`\"\"`) inside string literals, never backslash escaping. Runtime also rejects unclosed strings, common C-style operators/braces, unbalanced conditional-compilation blocks, export-only headers, BOM, hidden Unicode formatting/line separators, NUL, and other raw control characters before dispatch.\n\n" +
                    "## Write maintainable VBA\n\n" +
                    "- Keep the module's contiguous `Option ...` directives at the top and before declarations. Include `Option Explicit` in authored modules, and insert declarations only after the complete Option block. Preserve host ownership: keep workbook, worksheet, document, presentation, class, and UserForm event procedures in the component that owns those events.\n" +
                    "- Qualify Office objects deliberately and avoid `Select`, `Activate`, `Selection`, or implicit `ActiveWorkbook`/active-document state when a stable object reference is available. Use `Value2` and a Variant 2D array for bulk Excel range transfer instead of cell-by-cell loops when practical.\n" +
                    "- Scope error suppression narrowly. When changing application-wide flags such as `ScreenUpdating`, `EnableEvents`, `DisplayAlerts`, or calculation mode, capture their previous values and restore them on both success and failure.\n" +
                    "- For Office API declarations, verify the DLL entry point and signature against platform/vendor documentation or an existing trusted project declaration; do not guess parameter types. Use VBA7-compatible `PtrSafe` and `LongPtr` only for pointer or handle values, and conditional compilation only when cross-version compatibility is actually required. Do not introduce an unverified external reference when late binding or an existing reference is sufficient.\n" +
                    "- A successful mutation proves VBE-equivalent source read-back and returns the semantic actual type/name/change evidence; runtime retains the exact source hashes outside model context. `vbeNormalized=true` means literal text was normalized. It does not prove VBA compilation or runtime behavior. Do not claim the macro works solely from write success and do not invoke hidden macro backends to test it. State when Windows Office validation is still required.\n\n" +
                    "## Mutation and recovery\n\n" +
                    "- Runtime always reads current state, binds a guard through confirmation, journals intended state, and verifies read-back. A complete model-visible source read is still required before a second source mutation of the same module: internal verification does not silently refresh model context, and partial chunk reads do not clear this gate. Source-changing mutations create a source backup when prior code exists; rename instead journals both names and its hidden backend restores the original name on a verified failure. `expectedCodeSha256` is never a model argument. Re-read after stale detection and reconcile before any whole-source overwrite.\n" +
                    "- Mutations require confirmation unless `AutoConfirmToolActions` is enabled. Source backup cannot undo behavior already executed by a macro or event handler.\n" +
                    "- Whole-source creation supports `StdModule`, `ClassModule`, and blank code-only `MSForm`. Load `common.vba_userform_authoring` for runtime-generated controls and events. Designer/FRX state is outside this protocol. Delete supports only `StdModule` and `ClassModule`; document modules and UserForms are not deleted. For an exact historical restore, find scope `backups` and pass the chosen readable `target`; pass only `moduleName` when the intent is explicitly that module's latest backup. Raw backup ids are runtime-owned."),
                Skill(
                    "common.vba_userform_authoring",
                    "Code-only VBA UserForm authoring",
                    "Create or edit a blank VBA UserForm whose controls, layout, properties and events are generated entirely from source code.",
                    "# Code-only VBA UserForm Authoring\n\nUse a blank MSForm as a generated host shell and keep the complete semantic UI definition in code. Designer-time controls/properties and FRX assets are unsupported.\n\n## Structure\n\n- Create the form with common.vba_write_module and componentType=MSForm. Build controls from one UserForm_Initialize path with Me.Controls.Add, stable explicit names and deterministic layout. Set the form caption, size and every relevant runtime-settable property in code. Do not depend on manual Designer edits.\n- For a fixed control set, declare concrete Private WithEvents MSForms fields and assign each result of Controls.Add. For repeated controls, use a typed event-sink class per control and retain every sink in a form-level Collection; an unreferenced sink loses its events.\n- Put the public Show entry point in a StdModule. Use additional ClassModule components only when event sinks or reusable view logic are needed. Keep initialization idempotent for one instance and never append controls from repeatedly fired UserForm_Activate.\n\n## Editing and recovery\n\n- Find code through common.resources_find with scope=vba and read the exact semantic target; patch or replace it through the typed common.vba_* mutation tools. After an edit or restore, unload an already loaded form and instantiate it again; source changes do not rebuild a live instance.\n- Source backup/restore covers the code-only UI definition, not Designer/FRX state and not Office document changes already performed by event handlers. Do not describe chat undo/redo as VBA undo.\n- Reusable packages may include an MSForm component with code-behind stored as .form.vba, plus a StdModule launcher and optional ClassModule event sinks. Never pass exported .frm/.frx content. Install/remove is one journaled component transaction and fails closed on an existing unowned form, Designer controls, unverified Designer state or a type collision.\n- Keep embedded images, custom ActiveX controls, manual tab order and other Designer-dependent behavior out of this profile. Validate actual form creation and events on Windows x64 with Office x64."),
                Skill(
                    "common.tool_authoring",
                    "Tool authoring",
                    "Design reusable VBA tools safely.",
                    "# Tool Authoring\n\nUse this skill when creating or editing executable RNAssistant tools. Prefer an existing capability; tools are executable actions, not guidance. Only manifest-based VBA packages are supported.\n\n" +
                    "## Authoring flow\n\n- Find custom ids through common.capabilities_search. Read common.tools_definition_read with one exact id only when an edit depends on the existing implementation. It does not load the callable schema; common.capabilities_read does that separately.\n- Call common.tools_upsert with id plus complete native components when creating or changing implementation. Optional readme/useWhen/doNotUseWhen/limitations are selection documentation; omitted update fields are preserved. Use createOnly/updateOnly only when existence itself matters. Upsert performs the same complete validation before any confirmed save, so there is no separate model-facing validate call.\n- Package components belong to the Tool Library, not to the active document VBA project. Never stage or repair a tool package with common.vba_*; after an upsert error, correct the native components and call common.tools_upsert again.\n- Do not pass host, executor, parameters, enabled, agentCanRun, mutation flags, confirmation flags, risk, revision, URI, hash or storage path. Runtime derives manifest metadata and assigns conservative execution authority. Creating a tool does not execute it or complete the original Office task.\n\n" +
                    "## Package and manifest\n\n- Pass the outer `components` argument as a native ordered array of `{name,type,code}` objects, never stringified JSON. The first component is a StdModule with exactly one JSON manifest between `<RNAssistantTool>` and `</RNAssistantTool>` immediately before the entry function. Runtime comments every line of that manifest before validation/save so the module remains valid VBA. Supporting StdModule/ClassModule and blank code-only MSForm sources are allowed; exported .frm/.frx and document modules are not.\n- Inside the manifest, `components` is a different field: an ordered array of component-name strings such as `[\"Tool_AvgCalculator\"]`, never component objects. The manifest also requires protocolVersion=1, id, name, description, host, packageVersion, entryPoint, argumentOrder, formal parameters, mutatesDocument, agentCanRun and requiresConfirmation. Manifest host is exactly Excel, Word, or PowerPoint for the current package; an id prefix such as custom is a namespace, never a host. Runtime treats arbitrary VBA conservatively regardless of weaker manifest claims.\n- Formal parameters use a strict object schema with `additionalProperties:false`. Every argument has an explicit type and useful description. String, Long, Double and Boolean are supported, at most 30 positional arguments; each function argument is `ByVal`, follows argumentOrder and matches the schema. Optional arguments require a default.\n- A plumbing-shaped argument such as customerId is accepted only when its description contains `Domain identity rationale:` followed by why the caller must choose that domain value. Runtime URI/revision/cursor/guard/hash inputs are not legitimate custom parameters.\n- Component names use letters/numbers/underscore, start with a Latin letter and fit the 31-character VBE limit. The entry declaration is `Public Function ... As String`; return useful text and raise a normal VBA error on failure. Do not create a second JSON result envelope.\n\n" +
                    "## Safety\n\n- Use Option Explicit, deterministic names and explicit Office objects. Avoid Select/Activate, secrets, credentials and machine-specific paths. Validate domain inputs and restore application-wide state on both success and failure. Never auto-run generated code; save and later execution remain separately confirmation-controlled. Load common.vba_userform_authoring for code-only form rules."),
                Skill(
                    "common.skill_authoring",
                    "Skill authoring",
                    "Create markdown skills that guide agent behavior without executing actions.",
                    "# Skill Authoring\n\nUse this skill only when the user asks to create or edit RNAssistant guidance. Do not invent a skill merely because a workflow may benefit from one. When the request also includes a primary domain solution, inspect, implement, and verify that solution first; author the skill last from the workflow that actually succeeded. Skill creation never substitutes for an incomplete primary deliverable.\n\nA skill is concise Markdown guidance; it never executes actions or changes tool authority. Load an existing exact skill through `common.capabilities_read` when the edit depends on it. Keep the core under 500 lines and move optional detail into direct UTF-8 `references/*.md` files linked from the core. Read a needed reference with exact `id`/`referencePath`; use `action=next` only when `hasMore=true`. Offset, page size, revision, and package guards are runtime-owned.\n\n## Authoring contract\n\n- State a narrow purpose plus explicit **use when** and **do not use when** selection boundaries.\n- Give an ordered workflow with prerequisites before mutations, exact tool ids where stable, failure handling that preserves prior work, and evidence-based completion criteria. Skills define workflow and quality; loaded tool schemas remain authoritative for arguments. Do not copy a schema or runtime-owned fields into prose.\n- Put domain quality guidance in the skill, universal lifecycle/safety in the system prompt, and exact argument/output semantics in tool descriptions. Avoid duplicate rules that can drift.\n- Use `common.skills_upsert` only for core create/update; omitted core fields are preserved. Use `common.skills_reference_upsert` or `common.skills_reference_delete` for one complete exact reference, and `common.skills_delete` only for the complete skill. These are separate confirmed calls.\n- If executable behavior is needed, author a Tool separately. Built-in ids are reserved. Never store secrets or weaken runtime safety.\n\nRecommended sections: Purpose and selection; Inputs/prerequisites; Workflow; Quality and safety constraints; Failure/recovery; Verification and definition of done; Useful tools."),
                Skill(
                    "common.prompt_authoring",
                    "Prompt authoring",
                    "Review and improve RNAssistant editable prompts without weakening its protocol or safety.",
                    "# Prompt Authoring\n\nUse this skill only when the user asks to inspect or improve RNAssistant prompts.\n\n## Review first\n\n- Call `common.prompts_read` with `includeDefaults=true` before proposing a change. Compare all three Agent layers together: `SystemPrompt` owns universal operating order and completion; `AgentToolsPrompt` owns discovery/schema/call rules; `AgentSkillsPrompt` owns skill selection/loading. Chat uses `ChatSystemPrompt`; Plan uses `PlanSystemPrompt`. Helper prompts are separate and compatibility probes remain fixed.\n- Check affected skill bodies and current tool schemas before naming tools or arguments. Prefer one clear positive operating sequence with stage exit criteria. Keep domain-specific quality rules in skills and exact input/output details in tool descriptions; do not duplicate them across prompt layers. Add a focused regression for a recurring failure instead of accumulating contradictory warnings or hidden chain-of-thought requirements.\n\n## Preserve contracts and save narrowly\n\n- Preserve the current structured response and Tool Result v1 contracts. Each call contains only exact `name` and root object `arguments`; never include model-owned id/status or runtime-owned URI, revision, cursor, guard, or hash. Runtime assigns call IDs after validation and owns execution outcomes. Chat remains limited to `common.resources_find/read`.\n- Do not weaken confirmation, secret handling, batch restrictions, source-first execution, or effect-evidence rules. `TOOL_RESULT status=ok` does not by itself prove an applied effect.\n- Save exactly one setting per confirmed `common.prompts_save` call using `promptKey` and its complete value; never send several optional prompt fields. `systemPromptRole` accepts only `developer`, `system`, or `user`. Finish only after the save result verifies the requested setting; saved older prompt schemas still require explicit user review/reset."),
                Skill(
                    "common.html_workspace_authoring",
                    "HTML workspace authoring",
                    "Build, search, patch, and maintain local HTML pages, reports, interfaces, interactive visualizations, CSS, scripts, static JSON, and refreshable Office-bound data when visual presentation materially helps.",
                    "# HTML Workspace Authoring\n\nUse this skill for a local HTML page, report, visual comparison, interface, or interactive tool when HTML materially improves the requested result. Do not use it to replace a simple text answer or to avoid editing the requested Office/VBA source. Nontrivial HTML work is a discovery -> construction -> verification task and normally requires `common.task_tracking`.\n\n" +
                    "## 1. Understand and inspect\n\n" +
                    "- Before writing files, identify the page purpose, information architecture, source data, user actions, required states, constraints, and completion evidence. When the page depends on a workbook, macro, VBA source, or existing workspace, load the matching domain skills and inspect those sources first. Study requested macro behavior before choosing the data contract; do not replace source-specific requirements with a generic template.\n" +
                    "- For an existing workspace, use `common.resources_find` with `scope=html`, select the exact workspace/file/data target, and read its complete structure/source/text as needed. Provider, URI, revision, cursor, and page size are runtime-owned. Preserve working layout and behavior unless the user explicitly asks to replace them.\n\n" +
                    "## 2. Establish the live data contract\n\n" +
                    "- Discover the source with `common.resources_find`, inspect a bounded `common.resources_read` view, then call `common.html_data_bind` with `name`, the semantic `target`, `view` and `policy=exact|head`. Workspace configuration stores references only. Runtime resolves identity, exact revision and scope; never copy a tool call or payload into binding configuration.\n" +
                    "- Page code uses `const handle = await RN.resources.open(name)` and `for await (const batch of handle.stream({view:'table',limit:500})) { render(batch.rows, batch.columns); }`. Use exact saved binding names (`RN.resources.names` lists them), canonical column keys, bounded batches and explicit loading/error states. No eager data globals, header aliases or implicit transforms exist. For semantic columns, publish a validated schema and physical mapping, derive a virtual/materialized resource, and bind its semantic target.\n" +
                    "- A head binding resolves once per lease; continuation stays on that exact revision. Refresh observes canonical source authority without rewriting workspace history or duplicating JSON. Freeze changes the binding to an exact revision, not an embedded body. Close handles on cancellation or completion.\n\n" +
                    "## 3. Structure the workspace\n\n" +
                    "- For substantial HTML, create at least `index.html` (semantic structure and accessible labels), `styles.css` (all substantial presentation and responsive rules), and one focused script such as `app.js` (data adaptation, state, events, and rendering). Keep inline CSS/JS only for tiny self-contained artifacts. Add further focused files only when responsibilities are genuinely distinct.\n" +
                    "- The active HTML file is the entry page. Runtime injects every workspace CSS file into its head and every classic JavaScript file before its closing body in workspace order. Do not add local `<link>` or `<script src>` references and do not use ES module import/export. Never paste a library bundle into HTML or a workspace script.\n" +
                    "- Every workspace script runs on every entry page. Use an IIFE or one stable namespace, guard DOM lookups, and make initialization idempotent. Keep one clear orchestrator when script order matters.\n\n" +
                    "## 4. Use the tools exactly\n\n" +
                    "- Create a file or intentionally replace its complete source with `common.html_workspace_write_file`; its root `arguments` contains exactly `path` and `content`. Never nest another `arguments` object or pass kind, active file, preview state, or undeclared fields. Create static JSON with `common.html_data_write` root `name` and `json`.\n" +
                    "- Prefer `common.html_workspace_apply_patch` for an existing rich file. Pass root `path` and a native ordered `patch` array of exact `replace`, `replaceAll`, `insertBefore`, or `insertAfter` operations. Use `replaceAll` only intentionally. Delete only an exact readable path/name with `common.html_workspace_delete`.\n" +
                    "- `content`, `json`, `find`, and `text` are exact decoded strings. In the outer conversation JSON use `\\n` for a real line break and `\\\\` for one literal source backslash; source `\\n` or regex `\\d` therefore appears as `\\\\n` or `\\\\d`. Runtime stores decoded text unchanged.\n" +
                    "- Automatic static preflight follows every mutation. Read its issues, repair the smallest failing part, and retain requested interactions and visual quality. Never replace a rich implementation with a simplified placeholder just to clear an error.\n\n" +
                    "## 5. Use bundled ECharts\n\n" +
                    "- Choose one visual surface for one requested chart. If the deliverable is an ECharts/HTML page or visualization, do not also call `excel.create_chat_chart` for the same data; use the chat-chart tool only when the user explicitly asks for a separate chart artifact in chat or no HTML workspace is being authored.\n" +
                    "- RNAssistant provides local ECharts 5.6.0 automatically when HTML or JavaScript references the global `echarts`. It appears in the workspace tree as read-only `Dependencies/echarts.min.js` and loads before workspace scripts. Do not create `echarts.js`, copy minified vendor code, add a CDN, or add any `<script src>` tag.\n" +
                    "- Put only a semantic chart container in HTML and give it a real width plus explicit height/min-height in CSS before initialization. In JavaScript, initialize after the DOM/container is laid out: `var chart = echarts.getInstanceByDom(node) || echarts.init(node); chart.setOption(option);`. Guard missing/zero-sized containers, call `chart.resize()` from `ResizeObserver` when available (window resize fallback), and avoid creating a second instance on rerender.\n" +
                    "- Give each chart a useful title/tooltip/legend and honest units; pair color with labels/symbols. Provide adjacent text, labels, table, or accessible summary when the visual carries essential information. Handle empty, loading, and error states instead of rendering a blank panel.\n\n" +
                    "## 6. Build a professional interface\n\n" +
                    "- Design from the requested content and user task, not from a fixed template. Establish clear hierarchy: page context, primary content, controls, supporting details, and status/error feedback. Use sections, panels, summary blocks, or dense tables only when they fit the content; do not invent unrelated widgets or decorative filler.\n" +
                    "- Use CSS custom properties for a coherent visual system: color, typography, spacing, radii, borders, and shadows. Use consistent alignment, whitespace, and rhythm; avoid decorative clutter and a generic narrow centered box unless requested.\n" +
                    "- Default to `body { margin: 0; }`, a responsive full-page grid, readable line lengths, and breakpoints that reflow without clipped controls or horizontal page scrolling. Use semantic headings, native buttons/selects/inputs with visible labels, keyboard focus, sufficient contrast, and feedback for loading/error/selection changes.\n" +
                    "- Wire every requested filter/button to visible state and rerendering. Preserve selected state, format numbers/dates consistently, and do not leave decorative controls without handlers.\n\n" +
                    "## 7. Verify refresh and export\n\n" +
                    "- Render from bounded `RN.resources` batches at startup. After `common.html_data_refresh`, reopen the head binding and verify returned revision/coverage plus a user-visible value or mark. Tool success alone does not prove that data reached the page. Old leases deliberately keep their original exact snapshot.\n" +
                    "- Resource-bound pages require a resource host or an exact exported resource bundle; never claim that a standalone HTML file contains data merely because it contains binding metadata. Do not label an in-page button as live Office refresh outside RNAssistant. ECharts remains the bundled local dependency, with no CDN or copied vendor source.\n" +
                    "- Network fetch requires explicit origin permission; no remote frames, credentials, `mode:no-cors`, or embedded secrets.\n" +
                    "- Definition of done: requested sources were inspected; required HTML/CSS/JS and reference bindings exist; no working requirement was dropped; preflight has zero errors; bindings have exact view/coverage evidence; claimed refresh has bounded read-back plus visible render evidence; controls have handlers; and ECharts uses the loaded bundled dependency. Static preflight does not prove browser execution or visual appearance; state unverified UI boundaries explicitly.")
            };

            var hostProvider = adapter as IOfficeBuiltInSkillProvider;
            if (hostProvider != null)
            {
                result.AddRange((hostProvider.GetBuiltInSkills() ?? new SkillDefinition[0]).Where(skill => skill != null));
            }

            return result;
        }

        private static SkillDefinition Skill(string id, string name, string description, string body)
        {
            return new SkillDefinition
            {
                Id = id,
                Host = "Common",
                Name = name,
                Description = description,
                BodyMarkdown = body,
                Enabled = true,
                BuiltIn = true,
                Version = "1.0.0"
            };
        }
    }
}
