using System.Collections.Generic;
using System.Linq;
using RNAssistant.Core.Models;

namespace RNAssistant.Office.Services
{
    internal static class BuiltInSkillProvider
    {
        public static IReadOnlyList<SkillDefinition> GetSkills(IOfficeApplicationAdapter adapter)
        {
            var result = new List<SkillDefinition>
            {
                Skill(
                    "common.task_planning",
                    "Task planning",
                    "Create and maintain a visible step plan for complex Agent tasks.",
                    "# Task Planning\n\nUse a visible plan only when a task has several meaningful stages or the user asks for one. Do not create a plan for a direct answer or a single obvious action.\n\n- Call common.plan_create once with a concise goal and stable ordered step ids. Use only pending, in_progress, completed, blocked, or cancelled statuses.\n- A plan is presentation data, not execution authority and not proof of success. Continue to use exact tools normally.\n- After material progress, call common.plan_update with the stable plan id and the complete updated step list. Preserve step ids and mark completed only after the relevant TOOL_RESULT has ok=true.\n- If the current plan id or contents are not present in the conversation, call common.plan_read without id to read the active plan before updating it.\n- Mark a step blocked when work genuinely cannot continue; explain the blocker in the final answer.\n- Create a new plan for a different goal. Delete a plan only when the user asks or it was created by mistake.\n- Do not update the plan after every trivial tool call and do not expose hidden reasoning in plan text."),
                Skill(
                    "common.text_search_replace",
                    "Text search and replace",
                    "Find and safely replace literal or regex text in Office content.",
                    "# Text Search and Replace\n\n- Use the host search tool when you need discovery, coordinates, or a preview; it is not a mandatory precondition for replacement.\n- Prefer literal mode unless the user needs a pattern. Use regex capture groups only in regex mode.\n- Keep scope as narrow as practical and review returned coordinates/previews for broad or ambiguous edits.\n- Replacement tools read the current scope themselves under the mutation lock, enforce maxReplacements, and verify the result. Do not invent or pass match-count/hash guards.\n- Regex and bulk replacement require confirmation."),
                Skill(
                    "common.vba_code_editing",
                    "VBA code editing",
                    "Inspect, search, write/upsert, patch, delete, and restore VBA components safely.",
                    "# VBA Code Editing\n\n- Use the compact common.vba_* facade in Excel, Word, and PowerPoint. Call common.vba_read_module without moduleName to list component metadata, with moduleName to read bounded whole source, or with startLine/lineCount for an exact range. Use common.vba_search_code only when search is useful.\n- A separate read is not required before a mutation. Runtime reads and binds current state itself, checks it again after confirmation, creates a backup where prior source exists, and verifies read-back. expectedCodeSha256 is never a model argument. If a patch/delete becomes stale, retry it and inspect only if intent may no longer match. For a stale whole-source write derived from an earlier read, re-read and reconcile; retry unchanged only when a complete overwrite is intentional.\n- Use common.vba_write_module when you have the complete intended source. Its default upsert mode updates an existing component or creates a missing one. componentType matters only for creation. Invalid new names are normalized to a stable VBA identifier and the result returns the actual name. Use createOnly or updateOnly only when strict existence semantics matter.\n- Use common.vba_apply_patch for targeted edits and pass patch as a native JSON array, never stringified JSON. Each operation exposes only its relevant fields; use text for replacement content. Combine known edits for one module into one ordered array. replace requires exactly one match; replaceAll is explicit; insertBefore/insertAfter add line-safe blocks around one unique anchor; replaceLines is one-based and sees prior operations; regexReplace supports capture groups and a replacement limit.\n- After a range read, prefer replaceLines over copying a large multi-line fragment. Set replaceAll only after considering every occurrence. Never embed raw control characters; generate them at VBA runtime with ChrW$(n). A failed safe mutation is not permission to call hidden whole-module or macro backends.\n- VBA mutations require confirmation unless the user enabled AutoConfirmToolActions. This remains an execution boundary because snapshots recover source but cannot undo behavior of executable or auto-run VBA.\n- Whole-source write supports StdModule, ClassModule, and a blank MSForm/UserForm with code-behind. Code-only runtime controls created from source are supported; load common.vba_userform_authoring when authoring them. Designer-time controls/properties and FRX assets are outside these tools. Delete supports only StdModule and ClassModule; document modules and UserForms are not deleted. For restore, prefer an exact backupId from common.vba_list_backups; use moduleName only when restoring that module's latest backup is intentional."),
                Skill(
                    "common.vba_userform_authoring",
                    "Code-only VBA UserForm authoring",
                    "Create or edit a blank VBA UserForm whose controls, layout, properties and events are generated entirely from source code.",
                    "# Code-only VBA UserForm Authoring\n\nUse a blank MSForm as a generated host shell and keep the complete semantic UI definition in code. Designer-time controls/properties and FRX assets are unsupported.\n\n## Structure\n\n- Create the form with common.vba_write_module and componentType=MSForm. Build controls from one UserForm_Initialize path with Me.Controls.Add, stable explicit names and deterministic layout. Set the form caption, size and every relevant runtime-settable property in code. Do not depend on manual Designer edits.\n- For a fixed control set, declare concrete Private WithEvents MSForms fields and assign each result of Controls.Add. For repeated controls, use a typed event-sink class per control and retain every sink in a form-level Collection; an unreferenced sink loses its events.\n- Put the public Show entry point in a StdModule. Use additional ClassModule components only when event sinks or reusable view logic are needed. Keep initialization idempotent for one instance and never append controls from repeatedly fired UserForm_Activate.\n\n## Editing and recovery\n\n- Read or patch code through common.vba_* like any other component. After an edit or restore, unload an already loaded form and instantiate it again; source changes do not rebuild a live instance.\n- Source backup/restore covers the code-only UI definition, not Designer/FRX state and not Office document changes already performed by event handlers. Do not describe chat undo/redo as VBA undo.\n- Reusable packages may include an MSForm component with code-behind stored as .form.vba, plus a StdModule launcher and optional ClassModule event sinks. Never pass exported .frm/.frx content. Install/remove is one journaled component transaction and fails closed on an existing unowned form, Designer controls, unverified Designer state or a type collision.\n- Keep embedded images, custom ActiveX controls, manual tab order and other Designer-dependent behavior out of this profile. Validate actual form creation and events on Windows x64 with Office x64."),
                Skill(
                    "common.tool_authoring",
                    "Tool authoring",
                    "Design reusable pipeline or VBA tools safely.",
                    "# Tool Authoring\n\nUse this skill when creating or editing executable RNAssistant tools.\n\n- Prefer an existing capability. Create a tool only when the requested work needs a reusable missing capability.\n- Tools are executable actions, not guidance documents. Pipeline tools call existing exact tool ids through ordered pipeline.steps with object arguments.\n- Call common.tools_upsert with one effective definition: runtime creates a missing id or merges supplied fields into an existing tool, then validates before confirmation/save. Use createOnly or updateOnly only when strict existence semantics matter. Use common.tools_validate only for a requested no-save preflight.\n- Call common.tools_read with id only when existing fields must be inspected, or without id for a compact custom-tool list. parameters is the actual strict object JSON Schema, pipeline is an actual JSON object, and components is an actual array of VBA sources; never double-encode them as JSON strings.\n- The catalog refreshes after a confirmed upsert or on the next user run. Creating a tool does not complete the original Office task.\n- VBA tools are host-specific. Put the manifest and entry function in the first StdModule component; custom VBA execution remains confirmation-controlled.\n- parameters must contain properties, required, and additionalProperties:false. Every argument needs an explicit type and useful description; declare real defaults, enums, limits, and array items.\n- Do not store secrets in code or metadata, weaken safety flags, or shadow built-in ids."),
                Skill(
                    "common.vba_tool_authoring",
                    "VBA tool authoring",
                    "Create versioned RNAssistant VBA tool packages with a strict manifest and String-returning entry function.",
                    "# VBA Tool Authoring\n\nUse this skill only for reusable VBA tools. Prefer an existing built-in or pipeline tool first.\n\n" +
                    "## Package\n\n- The global AppData package is canonical. Put source in `src/*.bas`, `src/*.cls`, and `src/*.form.vba`.\n- The first component is a standard entry module. Supporting standard/class modules and blank code-only MSForms are allowed. An MSForm source contains only code-behind; exported .frm/.frx, document modules and other Designer state are unsupported. Load common.vba_userform_authoring for its runtime control/event profile.\n- Component names start with a Latin letter, contain only letters/numbers/underscore and are at most the VBE limit of 31 characters; entry functions use the project limit of 40. Use `RNA_<Tool>` for the entry module, `RNATool_<Tool>` for the function and `RNA_<Tool>_<Role>` for dependencies.\n\n" +
                    "## Manifest and signature\n\n- Put exactly one comment-delimited JSON object between `<RNAssistantTool>` and `</RNAssistantTool>` immediately before the entry function.\n- Required fields: protocolVersion=1, id, name, description, host, packageVersion, entryPoint, components, argumentOrder, formal parameters JSON Schema, mutatesDocument, agentCanRun and requiresConfirmation. Set agentCanRun=true only when Agent should select the package; VBA execution remains confirmation-controlled unless auto-confirm is enabled.\n- Use `additionalProperties:false`. Every parameter needs an explicit type and useful description. Only String, Long, Double and Boolean arguments are allowed, with at most 30 positional arguments. Every function argument is `ByVal`, follows argumentOrder and matches its schema type. Optional arguments require a schema default.\n- The entry declaration is `Public Function ... As String`. Return a concise useful String. Raise a normal VBA error for failure; RNAssistant creates the JSON result envelope. Do not add a VBA JSON parser or manually build a result envelope.\n\n" +
                    "## Code rules\n\n- Use `Option Explicit`, deterministic names and explicit Office object references. Avoid Select/Activate where a direct object reference works.\n- Do not embed secrets, network credentials or machine-specific paths. Validate sheet/range/document inputs before mutation and leave application-wide settings restored in an error handler.\n- Never auto-run newly generated code. Validate and save the package first; installation is a separate confirmed operation. Safety behavior after installation follows manifest metadata."),
                Skill(
                    "common.skill_authoring",
                    "Skill authoring",
                    "Create markdown skills that guide agent behavior without executing actions.",
                    "# Skill Authoring\n\nUse this skill when the user asks to create or edit RNAssistant guidance.\n\nA skill is a concise Markdown instruction file. It describes workflow, constraints, and preferred tools; it never executes actions itself. Agent context contains the enabled skill catalog with id, name, description, package revision, body size, and reference count. Load the complete Markdown body through common.skills_read when the catalog description matches the task, and reload it when matching data.loaded=true evidence is no longer fully present in active context. Keep the core body under 500 lines and split broad workflows into narrower skills. Put detailed UTF-8 Markdown directly under references/, link each file from SKILL.md, and explain when to read it. Read only needed chunks with common.skills_read referencePath/offset/maxChars. Use common.skills_upsert with referencePath and referenceMarkdown to create or replace one reference, and common.skills_delete with referencePath to delete one. Mutate the core and a reference in separate confirmed calls. If the requested skill needs a new executable capability, create and validate a tool separately instead of embedding executable logic in the skill. For the core, common.skills_upsert creates a missing id or preserves omitted fields on update. Read existing content only when the requested edit depends on it. Built-in skill ids are reserved. Never store secrets or weaken runtime safety.\n\nRecommended sections:\n\n- Purpose\n- Workflow\n- Constraints\n- Useful tools"),
                Skill(
                    "common.prompt_authoring",
                    "Prompt authoring",
                    "Review and improve RNAssistant editable prompts without weakening its protocol or safety.",
                    "# Prompt Authoring\n\nUse this skill only when the user asks to inspect or improve RNAssistant prompts.\n\n- Call common.prompts_read with includeDefaults=true before proposing a change.\n- All editable prompts use Markdown. Organize longer instructions with stable headings and short rule lists; keep service prompts compact.\n- Agent mode receives one RUNTIME_CONTEXT JSON object with strict function-style tools, a compact revisioned skill catalog, document identity, user context, and artifacts. Relevant complete skill instructions arrive only through a current non-truncated common.skills_read result whose top-level data.loaded=true; optional reference chunks are separate evidence.\n- Preserve the minimal response fields: message and tool_calls. Each tool call contains a unique id, exact name, and object arguments. Independent calls may be returned together and execute sequentially.\n- Chat mode has no tools. ContextCompactionPrompt owns durable summary criteria.\n- Do not weaken confirmation, secret handling, or the rule that tool success is established only by TOOL_RESULT ok=true.\n- common.prompts_save changes local settings and requires confirmation."),
                Skill(
                    "common.html_workspace_authoring",
                    "HTML workspace authoring",
                    "Build, inspect, search, patch, and maintain local HTML reports, dashboards, CSS, scripts, static JSON, and refreshable Office-bound data. Prefer it when the chat HTML preference is enabled or visual presentation materially helps.",
                    "# HTML Workspace Authoring\n\n## Inspect and edit\n\n- For an existing workspace, call common.html_workspace_read without arguments once for the compact manifest. Do not read every body. Use common.html_workspace_search for discovery and startLine/lineCount reads for only the needed source range.\n- Use common.html_workspace_upsert for new resources, small files, and intentional whole-source rewrites. Default mode=upsert creates or updates; use createOnly/updateOnly only when existence itself matters.\n- Use common.html_workspace_apply_patch for targeted edits to an existing HTML/CSS/JavaScript file. Pass patch as a native ordered array. A separate read is optional because runtime applies all operations atomically to current source. Prefer unique replace/insert anchors or replaceLines; use replaceAll only intentionally.\n- After material edits, call common.html_workspace_inspect as a static preflight. Fix errors; treat unresolved-reference warnings as review prompts because runtime-created DOM/data may be valid. This tool does not execute JavaScript or render WebView.\n- Use common.html_workspace_delete for removal. Workspace mutations are recoverable artifact revisions and do not require VBA-style backups.\n\n## Runtime model\n\n- The active HTML file is the entry page. RNAssistant injects every workspace CSS file into its head and every classic JavaScript file before its closing body in workspace order. Do not add local link/script references and do not use ES module import/export.\n- Every script runs on every active entry page. Use an IIFE or one stable namespace, avoid global collisions, and guard DOM lookups. Keep the main DOM in the entry HTML; split substantial styling and behavior into focused CSS and JavaScript files.\n- Default to a responsive accessible full-page layout with body margin 0; do not force a narrow centered card unless requested.\n\n## Data and safety\n\n- For Office-backed data that should stay current, use common.html_data_bind with an approved read-only source. Prefer transform=table for grids/charts and raw when the source already suits the page. Read it through window.RNAssistantData and handle missing, empty, and binding-error states.\n- Refresh bound data instead of copying Office values into scripts. Prefer common.html_data_freeze before intentionally converting a binding to static JSON.\n- Network fetch is allowed only through the RNAssistant host after the user explicitly allows the HTTP(S) origin. Do not rely on CDN scripts, remote frames, credentials, mode:no-cors, or embedded secrets.")
            };

            var hostProvider = adapter as IOfficeBuiltInSkillProvider;
            if (hostProvider != null)
            {
                result.AddRange((hostProvider.GetBuiltInSkills() ?? new SkillDefinition[0]).Where(skill => skill != null));
            }

            return result;
        }

        private static SkillDefinition Skill(string id, string name, string description, string body)
        {
            return new SkillDefinition
            {
                Id = id,
                Host = "Common",
                Name = name,
                Description = description,
                BodyMarkdown = body,
                Enabled = true,
                BuiltIn = true,
                Version = "1.0.0"
            };
        }
    }
}
