<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../RNAssistant.Core/RNAssistant.Core.Net8.csproj" />
    <Reference Include="Newtonsoft.Json" HintPath="../../packages/Newtonsoft.Json.13.0.3/lib/net6.0/Newtonsoft.Json.dll" />
  </ItemGroup>
</Project>
